# Copyright (c) 2018, Triad National Security, LLC.
# All rights reserved.
#
# This program was produced under U.S. Government contract 89233218CNA000001
# for Los Alamos National Laboratory (LANL), which is operated by Triad
# National Security, LLC for the U.S. Department of Energy/National Nuclear
# Security Administration.
#
# All rights in the program are reserved by Triad National Security, LLC,
# and the U.S. Department of Energy/National Nuclear Security Administration.
# The Government is granted for itself and others acting on its behalf a
# nonexclusive, paid-up, irrevocable worldwide license in this material to
# reproduce, prepare derivative works, distribute copies to the public,
# perform publicly and display publicly, and to permit others to do so.
#
# This software is provided under the BSD-3-Clause license.
# See the LICENSE file for full license text and additional terms.

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "swiftbat"
version = "0.1.7"
description = "Routines for dealing with data from BAT on the Neil Gehrels Swift Observatory"
readme = "README.md"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
authors = [
    {name = "David M. Palmer", email = "palmer@lanl.gov"}
]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Astronomy",
]
dependencies = [
    "astropy>=8",
    "astroquery>0.4.8",
    "numpy",
    "python-dateutil",
    "skyfield>=1.4",
    "swifttools",
]

[project.urls]
Homepage = "https://github.com/lanl/swiftbat_python/"

[project.scripts]
swinfo = "swiftbat.swinfo:swinfo_main"

[tool.setuptools]
packages = ["swiftbat"]

[tool.setuptools.package-data]
swiftbat = ["catalog", "recent_bcttb.fits.gz"]
